[package]
name = "auto_clicker"
version = "0.1.0"
edition = "2018"

[dependencies]
winapi = { version = "0.3", features = ["winuser"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
